//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carte()
        {
            this.Imprumuts = new HashSet<Imprumut>();
            this.Recenzies = new HashSet<Recenzie>();
            this.Stocs = new HashSet<Stoc>();
        }
    
        public int ID { get; set; }
        public string Titlu { get; set; }
        public string Autor { get; set; }
        public Nullable<int> AnPublicare { get; set; }
        public string ISBN { get; set; }
        public byte[] Imagine { get; set; }
        public string Descriere { get; set; }
        public Nullable<int> NumarPagini { get; set; }
        public string Dimensiune { get; set; }
        public string Editura { get; set; }
        public string Categorie { get; set; }
        public double Nota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imprumut> Imprumuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzie> Recenzies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoc> Stocs { get; set; }
    }
}
