//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cititor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cititor()
        {
            this.Imprumuts = new HashSet<Imprumut>();
            this.Notificares = new HashSet<Notificare>();
            this.Recenzies = new HashSet<Recenzie>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Persoana { get; set; }
        public System.DateTime DataInregistrare { get; set; }
        public Nullable<int> NrCartiImprumutate { get; set; }
    
        public virtual Persoana Persoana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imprumut> Imprumuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificare> Notificares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzie> Recenzies { get; set; }
    }
}
