//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imprumut
    {
        public int ID { get; set; }
        public Nullable<int> ID_Cititor { get; set; }
        public Nullable<int> ID_Carte { get; set; }
        public System.DateTime DataImprumut { get; set; }
        public System.DateTime TermenLimita { get; set; }
        public Nullable<System.DateTime> DataReturnare { get; set; }
        public string Stare { get; set; }
        public Nullable<System.DateTime> DataCerereReturnare { get; set; }
    
        public virtual Carte Carte { get; set; }
        public virtual Cititor Cititor { get; set; }
    }
}
