//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificare
    {
        public int ID { get; set; }
        public Nullable<int> ID_Cititor { get; set; }
        public string Tip_Notificare { get; set; }
        public string Mesaj { get; set; }
        public System.DateTime DataTrimitere { get; set; }
        public string Stare { get; set; }
    
        public virtual Cititor Cititor { get; set; }
    }
}
