//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaElectronica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recenzie()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Cititor { get; set; }
        public Nullable<int> ID_Carte { get; set; }
        public Nullable<int> Nota { get; set; }
        public string Comentariu { get; set; }
        public System.DateTime DataRecenzie { get; set; }
    
        public virtual Carte Carte { get; set; }
        public virtual Cititor Cititor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
